fixed crash on attempting to open new instance, required refactoring BrowserWindow to global
Uncaught Exception:
ReferenceError: win is not defined
    at click (C:\Users\jacks\AppData\Local\Programs\better-chatgpt\resources\app.asar\electron\index.cjs:53:9)
    at MenuItem.click (node:electron/js2c/browser_init:2:30166)
    at a._executeCommand (node:electron/js2c/browser_init:2:35562)